language: go
go:
- 1.4
- tip
install:
- npm install gulp
- make deps
script:
- make lint
- make test
- make build
notifications:
  urls:
      - https://webhooks.gitter.im/e/5a157feece092e3584cd
  on_success: change
  on_failure: always
  on_start: false
